#!/usr/bin/env nu
# Writes src/tables.bend from Doom's tables.c.
#
# The vanilla tables are not a formula: 33 sine and 204 tangent entries
# differ from int(sin/tan * 65536), so the source is the published table
# itself. Run once, with any GPL Doom source's tables.c:
#
#   http get https://raw.githubusercontent.com/chocolate-doom/chocolate-doom/master/src/tables.c | save /tmp/tables.c
#   tools/gen_tables.nu /tmp/tables.c | save --force src/tables.bend
#
# A list literal past a few thousand entries overflows Bend's parser, so
# each table is cut into 1024-entry defs that Tables.<name> appends.

const chunk = 1024
const tables = [[name, size]; [finesine, 10240], [finetangent, 4096], [tantoangle, 2049]]

# The entries of one C array, as two's complement U32 words.
def entries [src: string, name: string, size: int]: nothing -> list<int> {
  let pattern = ['(?s)' $name '\[' $size '\]\s*=\s*\{(?<body>.*?)\};'] | str join
  let body = $src | parse --regex $pattern | get body.0
  let vals = $body | parse --regex '(?<v>-?\d+)' | get v | into int
  if ($vals | length) != $size {
    error make {msg: $"($name): ($vals | length) entries, ($size) expected"}
  }
  $vals | each {|v| if $v < 0 { $v + 4294967296 } else { $v } }
}

# The defs for one table: a def per chunk, then the def that joins them.
def defs [src: string, name: string, size: int]: nothing -> list<string> {
  let chunks = entries $src $name $size | chunks $chunk | enumerate
  let parts = $chunks | each {|c|
    [$"def Tables.($name).($c.index)\(\) -> List<&2, U32>:", $"  [($c.item | str join ', ')]", ""]
  } | flatten
  let names = $chunks | each {|c| $"Tables.($name).($c.index)\(\)" } | str join ", "
  $parts | append [$"def Tables.($name)\(\) -> List<&2, U32>:", $"  List.concat\(&2, U32, [($names)]\)", ""]
}

def main [source: path]: nothing -> string {
  let src = open --raw $source
  let head = [
    "# Generated by tools/gen_tables.nu from Doom's tables.c; do not edit."
    "# Doom's fine sine (10240 entries: 1.25 turns, so index + 2048 is the"
    "# cosine), fine tangent (4096) and arctangent (2049) tables, exact to"
    "# the vanilla bit, as two's complement U32 words."
    "import Base"
    ""
  ]
  $head | append ($tables | each {|t| defs $src $t.name $t.size } | flatten) | str join "\n"
}
