#!/usr/bin/env nu
# Writes src/sfx_taps.bend: the taps of SDL3's resampler that a sound at
# 11025 or 22050 Hz meets on its way to 44100 Hz. SDL builds its filter
# at run time, in single precision (GenerateResamplerFilter in
# src/audio/SDL_audioresample.c: a Kaiser window over a sinc, a cubic
# through every four points), so this is that code again with every
# operation rounded to single precision as C rounds it: a double holds
# the exact result of two singles added, multiplied or divided closely
# enough that rounding it once more gives the single C gets, and the
# same holds for the square root. The sine is the one step that is not
# SDL's own arithmetic: glibc's sinf, taken here as the double sine
# rounded. tests/sfx.bend pins the table's hash, and the ticket records
# the table read from a running Chocolate Doom's memory.
#
# At these rates the source position steps by a whole number of the
# filter's eight phases, so the cubic's fraction is always 0 and only
# its constant term counts, and only the even phases are met. Run with
# the source of the SDL3 the flake's Chocolate Doom links:
#
#   tools/gen_sfx_taps.nu (nix build --no-link --print-out-paths --inputs-from . nixpkgs#sdl3.src) | save --force src/sfx_taps.bend

# A double rounded to the nearest single, ties to even.
def f32 []: float -> float {
  let x = $in
  if $x == 0 { return 0.0 }
  let mag = $x | math abs
  let guess = $mag | math log 2 | math floor
  let e = if 2.0 ** $guess > $mag { $guess - 1 } else if 2.0 ** ($guess + 1) <= $mag { $guess + 1 } else { $guess }
  let unit = 2.0 ** ($e - 23)
  let m = $mag / $unit
  let low = $m | math floor
  let rest = $m - $low
  let up = $rest > 0.5 or ($rest == 0.5 and $low mod 2 == 1)
  (if $up { $low + 1 } else { $low }) * $unit * (if $x < 0 { -1 } else { 1 })
}

# A single's bits.
def bits []: float -> int {
  let x = $in
  if $x == 0 { return 0 }
  let mag = $x | math abs
  let e = 0..<64 | each { 0 - $in } | where { 2.0 ** $in <= $mag } | first
  let m = $mag / 2.0 ** ($e - 23) | into int
  (if $x < 0 { 2147483648 } else { 0 }) + ($e + 127) * 8388608 + $m - 8388608
}

# BesselI0.
def bessel [x: float]: nothing -> float {
  let x = $x * ($x * 0.25) | f32
  mut sum = 0.0
  mut i = 1.0
  mut t = 1.0
  while $t >= $sum * 1.1920928955078125e-07 {
    $sum = $sum + $t | f32
    $t = $t * ($x / ($i * $i) | f32) | f32
    $i = $i + 1
  }
  $sum
}

# One define of the source, checked against what this port assumes.
def define [src: string, name: string, want: int] {
  let got = $src | parse --regex ('#define ' + $name + '\s+\(?(?<v>[^\s)]+)') | get v
  if ($want | into string) not-in $got { error make {msg: $"($name) is ($got), not ($want)"} }
}

def main [sdl: path]: nothing -> string {
  let src = open --raw ($sdl | path join src/audio/SDL_audioresample.c)
  define $src RESAMPLER_ZERO_CROSSINGS 6
  define $src RESAMPLER_BITS_PER_ZERO_CROSSING 3
  let db = $src | parse --regex 'const float dB = (?<v>[\d.]+)f;' | get v.0 | into float
  let k = $src | parse --regex 'const float beta = (?<k>[\d.]+)f \* \(dB - (?<off>[\d.]+)f\);' | first
  let pi = 3.14159265358979323846 | f32
  let per = 24
  let size = 6 * $per
  let beta = ($k.k | into float | f32) * ($db - ($k.off | into float | f32) | f32) | f32
  let bessel_beta = bessel $beta
  let sinc = 0..<$per | each {|i| ($i * ($pi / $per | f32) | f32 | math sin | f32) / $pi | f32 }
  let filter = [1.0] ++ (1..$size | each {|i|
    let b = (bessel ($beta * (($size * $size - $i * $i) / ($size * $size) | f32 | math sqrt | f32) | f32)) / $bessel_beta | f32
    let s = $sinc | get ($i mod $per) | if ($i // $per) mod 2 == 1 { 0 - $in } else { $in }
    $b * (($s * $per | f32) / $i | f32) | f32
  })
  let rows = [0 2 4 6] | each {|phase|
    (5..0 | each {|j| $filter | get ((8 * $j + $phase) * 3) }) ++ (0..5 | each {|j| $filter | get ((8 * $j + 8 - $phase) * 3) })
  }
  let hash = $rows | flatten | each { bits } | reduce --fold 2166136261 {|x, h| (($h | bits xor $x) * 16777619) mod 4294967296 }
  let show = {|x| if $x < 0 { $"F32.neg\((0 - $x)\)" } else { $"($x)" } }
  [
    "# Generated by tools/gen_sfx_taps.nu from SDL 3.4.14's"
    "# src/audio/SDL_audioresample.c; do not edit. The resampler's twelve"
    "# taps at its phases 0, 2, 4 and 6 of 8, the constant term of each"
    "# tap's cubic, oldest sample first. The FNV-1a hash of their bits is"
    $"# ($hash)."
    "import Base"
    ""
    "def SfxTaps.rows() -> List<&2, List<&2, F32>>:"
    $"  [($rows | each {|r| $'[($r | each $show | str join ", ")]' } | str join ', ')]"
    ""
  ] | str join "\n"
}
