#!/usr/bin/env python3
"""Writes src/tables.bend from Doom's tables.c.

The vanilla tables are not a formula: 33 sine and 204 tangent entries
differ from int(sin/tan * 65536), so the source is the published table
itself. Run once, with any GPL Doom source's tables.c:

    curl -sSL https://raw.githubusercontent.com/chocolate-doom/chocolate-doom/master/src/tables.c -o /tmp/tables.c
    python3 tools/gen_tables.py /tmp/tables.c > src/tables.bend

A list literal past a few thousand entries overflows Bend's parser, so
each table is cut into 1024-entry defs that Tables.<name> appends.
"""
import re
import sys

CHUNK = 1024
TABLES = [("finesine", 10240), ("finetangent", 4096), ("tantoangle", 2049)]


def table(src, name, size):
    m = re.search(name + r"\[" + str(size) + r"\]\s*=\s*\{(.*?)\};", src, re.S)
    vals = [int(x) for x in re.findall(r"-?\d+", m.group(1))]
    assert len(vals) == size, (name, len(vals))
    return [v & 0xFFFFFFFF for v in vals]


def main():
    src = open(sys.argv[1]).read()
    out = ["# Generated by tools/gen_tables.py from Doom's tables.c; do not edit.",
           "# Doom's fine sine (10240 entries: 1.25 turns, so index + 2048 is the",
           "# cosine), fine tangent (4096) and arctangent (2049) tables, exact to",
           "# the vanilla bit, as two's complement U32 words.",
           "import Base", ""]
    for name, size in TABLES:
        vals = table(src, name, size)
        chunks = [vals[i:i + CHUNK] for i in range(0, size, CHUNK)]
        for k, chunk in enumerate(chunks):
            out.append(f"def Tables.{name}.{k}() -> List<&2, U32>:")
            out.append("  [" + ", ".join(map(str, chunk)) + "]")
            out.append("")
        parts = [f"Tables.{name}.{k}()" for k in range(len(chunks))]
        out.append(f"def Tables.{name}() -> List<&2, U32>:")
        out.append("  List.concat(&2, U32, [" + ", ".join(parts) + "])")
        out.append("")
    sys.stdout.write("\n".join(out))


main()
