#!/usr/bin/env nu
# Writes src/opl_tables.bend from Chocolate Doom's source: Nuked OPL3's
# log-sine and exponent ROMs from opl/opl3.c, and DMX's frequency curve
# and volume mapping from src/i_oplmusic.c. Run with the source of the
# Chocolate Doom the flake pins:
#
#   tools/gen_opl_tables.nu (nix build --no-link --print-out-paths --inputs-from . nixpkgs#chocolate-doom.src) | save --force src/opl_tables.bend

const tables = [
  [file, c, name, size];
  [opl/opl3.c, logsinrom, logsin, 256]
  [opl/opl3.c, exprom, exp, 256]
  [src/i_oplmusic.c, frequency_curve, freq, 668]
  [src/i_oplmusic.c, volume_mapping_table, volume, 128]
]

# The entries of one C array, its comments dropped.
def entries [src: string, c: string, size: int]: nothing -> list<int> {
  let body = $src | lines | each { str replace --regex '//.*' '' } | str join "\n"
    | parse --regex (['(?s)' $c '\[\d*\]\s*=\s*\{(?<body>.*?)\};'] | str join) | get body.0
  let vals = $body | split row ',' | str trim | where $it != '' | into int
  if ($vals | length) != $size {
    error make {msg: $"($c): ($vals | length) entries, ($size) expected"}
  }
  $vals
}

def main [chocolate: path]: nothing -> string {
  let head = [
    "# Generated by tools/gen_opl_tables.nu from Chocolate Doom 3.1.1's"
    "# opl/opl3.c and src/i_oplmusic.c; do not edit. Nuked OPL3's log-sine"
    "# (256) and exponent (256) ROMs, and DMX's frequency curve (668, its"
    "# last entry the overrun i_oplmusic.c keeps) and volume mapping (128)."
    "import Base"
    ""
  ]
  $head | append ($tables | each {|t|
    let src = open --raw ($chocolate | path join $t.file)
    [$"def OplTables.($t.name)\(\) -> List<&2, U32>:", $"  [(entries $src $t.c $t.size | str join ', ')]", ""]
  } | flatten) | str join "\n"
}
